targets:
  $default:
    builders:
      copy_with_generator:
        # enabled: true
        generate_for:
          - example/*

builders:
  copy_with_generator:
    import: "package:copy_with_generator/builder.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["copy_with_generator.g.part"]}
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
    build_to: cache
    # target: ":copy_with_generator"