name: copy_with_generator
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  copy_with:
    git:
      url: https://github.com/urusai88/copy_with.git
      path: copy_with
  source_gen: ^0.9.0
  analyzer: ">=0.40.0"
  build: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
