name: copy_with_generator
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  copy_with:
    path: ./../copy_with
  source_gen: 0.9.10+1
  analyzer: 0.41.2
  build: 1.6.1

dev_dependencies:
  build_runner: 1.11.0